import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const macanSans = localFont({
  src: [
    {
      path: "../public/fonts/MacanPanWeb-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/MacanPanWeb-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-macan-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${macanSans.className} ${macanSans.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
